ENTITY_MAPPING = {
    'ANIMALS': [
        'lamb',
        'tiger',
        'sheep',
        'dove',
        'grasshopper',
        'robin',
        'sparrow',
        'bird',
    ],
    'HUMAN': [
        'shepherd',
        'little boy',
        'little girl',
        'child',
        'father',
        'mother',
        'chimney sweeper',
        'infant',
        'babes',
        'soldier',
        'sex',
        'son',
        'breast',
        'plague',
    ],
    'RELIGIOUS_FIGURES': [
        'angel',
        'god',
        'divine image',
        'prays',
        'coffin',
        'heaven',
        'holy',
        'virgin',
        'church',
        'priest',
    ],
    'EMOTIONS': [
        'joy',
        'merry',
        'cheer',
        'happy',
        'weep',
        'smile',
        'sweet',
        'pretty',
        'laughing',
        'love',
        'pity',
        'tear',
        'mercy',
        'wailing',
        'lost',
        'groan',
        'fear',
        'troubled',
        'cry',
        'poor',
        'deadly',
        'doubts',
        'reason',
        'dismay',
        'rejoicing',
        'angrypride',
        'shame',
        'poverty',
        'shriek',
        'surprise',
        'unrest',
        'piteous',
        'famished',
        'cruelty',
    ],
    'EVOCATIVE_IMAGES': ['death', 'light'],
    'COLORS': ['green', 'white', 'dark'],
    'TIMES_OF_THE_DAY': ['morning', 'night', 'day', 'noonday'],
    'NATURE': [
        'hill',
        'meadow',
        'flower',
        'tree',
        'snow',
        'oak',
        'cheery',
        'nest',
        'grass',
        'pebble',
        'root',
        'garden',
        'valley',
        'desert',
        'lily',
        'rose',
        'thorn',
        'merry sparrow',
    ],
}

TRAIN_DATA = [
    ("A robin flew from the tree", {"entities": [(2, 7, "ANIMALS")]}),
    ("A merry sparrow flew from the tree", {"entities": [(2, 13, "ANIMALS")]})]